### ISSUE TITLE
Manually get gradient with respect to the input x?

### ISSUE THREAD

**Issue by jmsull** [PumasAI/SimpleChains.jl#145]
If I have a SimpleChain with parameters $p$ and input $x$, is there a way to easily (or not so easily) get the gradient with respect to $x$ without calling an external AD package?

I ask in particular because I am wondering if this [comment](https://github.com/PumasAI/SimpleChains.jl/blob/882170615854f441e56d52d1f7c2188c3b122a92/src/chain_rules.jl#L27) and the subsequent commented-out code means this would not be hard to implement quickly?

Thanks in advance!

**Comment by chriselrod** [comment]
It'd make a good first PR!
Notice how `chain_valgrad_entry!` calls `pullback_param!`:
https://github.com/PumasAI/SimpleChains.jl/blob/882170615854f441e56d52d1f7c2188c3b122a92/src/simple_chain.jl#L585-L601

While `chain_valgrad!` calls `pullback!`:
https://github.com/PumasAI/SimpleChains.jl/blob/882170615854f441e56d52d1f7c2188c3b122a92/src/simple_chain.jl#L615-L627

`pullback!` calculates the derivatives with respect to the inputs and parameters, while `pullback_param!` is inputs-only.
So, you'd need to:
1. Add a different `valgrad!` functions that calls `chain_valgrad!` directly instead of calling `chain_valgrad_entry!`.
2. Update the `num_bytes` of your new `valgrad!` method, adding the `sizeof` the gradient w/ respect to `x`:
https://github.com/PumasAI/SimpleChains.jl/blob/882170615854f441e56d52d1f7c2188c3b122a92/src/simple_chain.jl#L541-L554

**Comment by jmsull** [comment]
Thanks for the guidance, I will look and give it a shot

**Comment by jmsull** [comment]
Thanks for addressing this!

**Comment by jmsull** [comment]
@chriselrod Sorry if I missed something obvious, but how can I get the gradient of the simplechain **without** the loss? 

I.e. when I try to call valgrad! as [you do in runtests](https://github.com/PumasAI/SimpleChains.jl/blob/f028d69679d47f11d35e7f311abdf0d1d3bfab9c/test/runtests.jl#L114), I get an assertion error from [this line](https://github.com/PumasAI/SimpleChains.jl/blob/f028d69679d47f11d35e7f311abdf0d1d3bfab9c/src/simple_chain.jl#L562) unless I append a loss layer.

Why should I not be able to take the gradient of the chain without the loss layer? 

Thanks in advance!
